language: python

python:
      - "3.3"
      - "3.4"
      - "3.5"
      - "3.6"
      - "3.7-dev"
install:
    - "pip install -r requirements.txt"
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install python-coveralls ; fi
script:
    - "pytest -n 4 --cov=fades"
after_script:
    - "flake8 fades --max-line-length=99 --select=E,W,F,C,N"

# report coverage to coveralls.io
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then coveralls; fi

cache:
  apt: true
  pip: true
